"""replace prekey_bundles with simplified identity_keys

Revision ID: 55a96bcef3f7
Revises: c7a1175b260b
Create Date: 2026-08-01 11:20:51.064568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55a96bcef3f7'
down_revision: Union[str, None] = 'c7a1175b260b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('public_key_b64', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_keys_user_id'), 'identity_keys', ['user_id'], unique=True)
    op.drop_index('ix_prekey_bundles_user_id', table_name='prekey_bundles')
    op.drop_table('prekey_bundles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prekey_bundles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('identity_key_public', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('signed_prekey_public', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('signed_prekey_signature', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('one_time_prekey_public', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('registration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='prekey_bundles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prekey_bundles_pkey')
    )
    op.create_index('ix_prekey_bundles_user_id', 'prekey_bundles', ['user_id'], unique=False)
    op.drop_index(op.f('ix_identity_keys_user_id'), table_name='identity_keys')
    op.drop_table('identity_keys')
    # ### end Alembic commands ###
