"""initial schema

Revision ID: 5fd79f0195f3
Revises: 
Create Date: 2026-07-24 05:55:17.637560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fd79f0195f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_ref_hash', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('banned_by_mod_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banned_contacts_contact_ref_hash'), 'banned_contacts', ['contact_ref_hash'], unique=True)
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('image', 'video', 'audio', name='mediatype'), nullable=False),
    sa.Column('storage_key', sa.String(length=256), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('scan_status', sa.Enum('pending', 'clear', 'flagged', 'error', name='mediascanstatus'), nullable=False),
    sa.Column('scan_provider', sa.String(length=32), nullable=True),
    sa.Column('scan_completed_at', sa.DateTime(), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('available', 'viewing', 'consumed', 'held_for_report', name='medialifecyclestatus'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('session_started_at', sa.DateTime(), nullable=True),
    sa.Column('session_last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('held_for_report', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_message_id'), 'media', ['message_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('handle', sa.String(length=32), nullable=False),
    sa.Column('contact_ref_hash', sa.String(length=128), nullable=False),
    sa.Column('dob_attested', sa.DateTime(), nullable=False),
    sa.Column('age_gate_accepted_at', sa.DateTime(), nullable=False),
    sa.Column('nsfw_opt_in', sa.Boolean(), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('carrier_age_check_result', sa.String(length=16), nullable=True),
    sa.Column('carrier_age_check_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'banned', 'shadowbanned', 'suspended_dm', name='userstatus'), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('is_moderator', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_contact_ref_hash'), 'users', ['contact_ref_hash'], unique=True)
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('uploader_user_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=256), nullable=True),
    sa.Column('scan_provider', sa.String(length=32), nullable=True),
    sa.Column('scan_result_summary', sa.Text(), nullable=True),
    sa.Column('ncmec_report_status', sa.String(length=32), nullable=True),
    sa.Column('ncmec_report_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('intent_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('location_label', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('active', 'deleted_by_author', 'expired', 'removed_by_mod', name='poststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_table('prekey_bundles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('identity_key_public', sa.String(), nullable=False),
    sa.Column('signed_prekey_public', sa.String(), nullable=False),
    sa.Column('signed_prekey_signature', sa.String(), nullable=False),
    sa.Column('one_time_prekey_public', sa.String(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prekey_bundles_user_id'), 'prekey_bundles', ['user_id'], unique=False)
    op.create_table('dm_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('user_a_id', sa.UUID(), nullable=False),
    sa.Column('user_b_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ciphertext', sa.Text(), nullable=True),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('held_for_report', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['dm_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('underage', 'threat_or_violence', 'non_consensual', 'solicitation', 'harassment', 'unsolicited_explicit_media', 'scam', 'spam', 'other', name='reportreason'), nullable=False),
    sa.Column('detail_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'under_review', 'resolved', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('mod_action', sa.String(length=64), nullable=True),
    sa.Column('mod_note', sa.Text(), nullable=True),
    sa.Column('mod_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['dm_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_reported_user_id'), 'reports', ['reported_user_id'], unique=False)
    op.create_table('message_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('reported_message_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('thread_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['dm_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_reports')
    op.drop_index(op.f('ix_reports_reported_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('dm_threads')
    op.drop_index(op.f('ix_prekey_bundles_user_id'), table_name='prekey_bundles')
    op.drop_table('prekey_bundles')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('evidence_records')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_index(op.f('ix_users_contact_ref_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_media_message_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_banned_contacts_contact_ref_hash'), table_name='banned_contacts')
    op.drop_table('banned_contacts')
    # ### end Alembic commands ###
