"""add thread_reads table for unread tracking

Revision ID: c7a1175b260b
Revises: e2eb9c8d993c
Create Date: 2026-07-26 06:43:01.515529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a1175b260b'
down_revision: Union[str, None] = 'e2eb9c8d993c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_reads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['dm_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_reads_thread_id'), 'thread_reads', ['thread_id'], unique=False)
    op.create_index(op.f('ix_thread_reads_user_id'), 'thread_reads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_reads_user_id'), table_name='thread_reads')
    op.drop_index(op.f('ix_thread_reads_thread_id'), table_name='thread_reads')
    op.drop_table('thread_reads')
    # ### end Alembic commands ###
