"""add nsfw flag to media

Revision ID: e2eb9c8d993c
Revises: 2304ffaca963
Create Date: 2026-07-25 05:58:51.366412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2eb9c8d993c'
down_revision: Union[str, None] = '2304ffaca963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('nsfw', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'nsfw')
    # ### end Alembic commands ###
